### PR TITLE
Update Python shebang and syntax for Python3

### PR DESCRIPTION
**Pull request by tbalch-tri**

### CODE REVIEW

**Review by pauldrewstri — COMMENTED** [review]
Just curious, is this required to run with noetic?  Does `python` not link to python3?

**Comment by pauldrewstri** [comment]
I guess my actual quesion is does this work with melodic.  If yes, then ship it.

**Comment by tbalch-tri** [comment]
It does still target python3 in 20.04, but you get a `ImportError: No module named yaml` error if you use `python` instead of `python3` in the shebang. There is an error with importing `tf2_ros` in our `state_pub.py` script. I haven't found a great fix for it yet in 18.04, but worst case we can change the shebang back to `python` there until the cars are running the new jetson image.

**Comment by tbalch-tri** [comment]
Or we can just wait on merging the `scale-cars-core` PR until that time

**Comment by pauldrewstri** [comment]
Alrighty.  I'm ok with either, I doubt we will be updating this package before we switch to 20.04

**Pull request merged**
